apiVersion: v1
kind: ConfigMap
metadata:
  name: vm-xml
data:
  xml.properties: |
   <domain type='kvm' id='1'>
     <name>default_vm-cirros</name>
     <uuid>0d2a2043-41c0-59c3-9b17-025022203668</uuid>
     <metadata>
       <kubevirt xmlns="http://kubevirt.io">
         <uid/>
       </kubevirt>
     </metadata>
     <memory unit='KiB'>262144</memory>
     <currentMemory unit='KiB'>262144</currentMemory>
     <vcpu placement='static'>1</vcpu>
     <iothreads>1</iothreads>
     <sysinfo type='smbios'>
       <system>
         <entry name='manufacturer'>KubeVirt</entry>
         <entry name='product'>None</entry>
         <entry name='uuid'>0d2a2043-41c0-59c3-9b17-025022203668</entry>
         <entry name='family'>KubeVirt</entry>
       </system>
     </sysinfo>
     <os>
       <type arch='x86_64' machine='pc-q35-rhel9.4.0'>hvm</type>
       <boot dev='hd'/>
       <smbios mode='sysinfo'/>
     </os>
     <features>
       <acpi/>
     </features>
     <cpu mode='custom' match='exact' check='full'>
       <model fallback='forbid'>Westmere</model>
       <vendor>Intel</vendor>
       <topology sockets='1' dies='1' clusters='1' cores='1' threads='1'/>
       <feature policy='require' name='pclmuldq'/>
       <feature policy='require' name='vmx'/>
       <feature policy='require' name='pcid'/>
       <feature policy='require' name='x2apic'/>
       <feature policy='require' name='tsc-deadline'/>
       <feature policy='require' name='hypervisor'/>
       <feature policy='require' name='vme'/>
       <feature policy='require' name='ss'/>
       <feature policy='require' name='arat'/>
       <feature policy='require' name='tsc_adjust'/>
       <feature policy='require' name='umip'/>
       <feature policy='require' name='spec-ctrl'/>
       <feature policy='require' name='stibp'/>
       <feature policy='require' name='arch-capabilities'/>
       <feature policy='require' name='ssbd'/>
       <feature policy='require' name='pdpe1gb'/>
       <feature policy='require' name='rdtscp'/>
       <feature policy='require' name='ibpb'/>
       <feature policy='require' name='ibrs'/>
       <feature policy='require' name='amd-stibp'/>
       <feature policy='require' name='amd-ssbd'/>
       <feature policy='require' name='skip-l1dfl-vmentry'/>
       <feature policy='require' name='pschange-mc-no'/>
       <feature policy='require' name='gds-no'/>
       <feature policy='require' name='vmx-ins-outs'/>
       <feature policy='require' name='vmx-true-ctls'/>
       <feature policy='require' name='vmx-store-lma'/>
       <feature policy='require' name='vmx-activity-hlt'/>
       <feature policy='require' name='vmx-activity-wait-sipi'/>
       <feature policy='require' name='vmx-vmwrite-vmexit-fields'/>
       <feature policy='require' name='vmx-apicv-xapic'/>
       <feature policy='require' name='vmx-ept'/>
       <feature policy='require' name='vmx-desc-exit'/>
       <feature policy='require' name='vmx-rdtscp-exit'/>
       <feature policy='require' name='vmx-apicv-x2apic'/>
       <feature policy='require' name='vmx-vpid'/>
       <feature policy='require' name='vmx-wbinvd-exit'/>
       <feature policy='require' name='vmx-unrestricted-guest'/>
       <feature policy='require' name='vmx-shadow-vmcs'/>
       <feature policy='require' name='vmx-ept-execonly'/>
       <feature policy='require' name='vmx-page-walk-4'/>
       <feature policy='require' name='vmx-ept-2mb'/>
       <feature policy='require' name='vmx-ept-1gb'/>
       <feature policy='require' name='vmx-invept'/>
       <feature policy='require' name='vmx-invept-single-context'/>
       <feature policy='require' name='vmx-invept-all-context'/>
       <feature policy='require' name='vmx-invvpid'/>
       <feature policy='require' name='vmx-invvpid-single-addr'/>
       <feature policy='require' name='vmx-invvpid-all-context'/>
       <feature policy='require' name='vmx-intr-exit'/>
       <feature policy='require' name='vmx-nmi-exit'/>
       <feature policy='require' name='vmx-vnmi'/>
       <feature policy='require' name='vmx-preemption-timer'/>
       <feature policy='require' name='vmx-vintr-pending'/>
       <feature policy='require' name='vmx-tsc-offset'/>
       <feature policy='require' name='vmx-hlt-exit'/>
       <feature policy='require' name='vmx-invlpg-exit'/>
       <feature policy='require' name='vmx-mwait-exit'/>
       <feature policy='require' name='vmx-rdpmc-exit'/>
       <feature policy='require' name='vmx-rdtsc-exit'/>
       <feature policy='require' name='vmx-cr3-load-noexit'/>
       <feature policy='require' name='vmx-cr3-store-noexit'/>
       <feature policy='require' name='vmx-cr8-load-exit'/>
       <feature policy='require' name='vmx-cr8-store-exit'/>
       <feature policy='require' name='vmx-flexpriority'/>
       <feature policy='require' name='vmx-vnmi-pending'/>
       <feature policy='require' name='vmx-movdr-exit'/>
       <feature policy='require' name='vmx-io-exit'/>
       <feature policy='require' name='vmx-io-bitmap'/>
       <feature policy='require' name='vmx-mtf'/>
       <feature policy='require' name='vmx-msr-bitmap'/>
       <feature policy='require' name='vmx-monitor-exit'/>
       <feature policy='require' name='vmx-pause-exit'/>
       <feature policy='require' name='vmx-secondary-ctls'/>
       <feature policy='require' name='vmx-exit-nosave-debugctl'/>
       <feature policy='require' name='vmx-exit-load-perf-global-ctrl'/>
       <feature policy='require' name='vmx-exit-ack-intr'/>
       <feature policy='require' name='vmx-exit-save-pat'/>
       <feature policy='require' name='vmx-exit-load-pat'/>
       <feature policy='require' name='vmx-exit-save-efer'/>
       <feature policy='require' name='vmx-exit-load-efer'/>
       <feature policy='require' name='vmx-exit-save-preemption-timer'/>
       <feature policy='require' name='vmx-entry-noload-debugctl'/>
       <feature policy='require' name='vmx-entry-ia32e-mode'/>
       <feature policy='require' name='vmx-entry-load-perf-global-ctrl'/>
       <feature policy='require' name='vmx-entry-load-pat'/>
       <feature policy='require' name='vmx-entry-load-efer'/>
     </cpu>
     <clock offset='utc'/>
     <on_poweroff>destroy</on_poweroff>
     <on_reboot>restart</on_reboot>
     <on_crash>destroy</on_crash>
     <devices>
       <emulator>/usr/libexec/qemu-kvm</emulator>
       <disk type='file' device='disk' model='virtio-non-transitional'>
         <driver name='qemu' type='qcow2' cache='none' error_policy='stop' discard='unmap'/>
         <source file='/var/run/kubevirt-ephemeral-disks/disk-data/containerdisk/disk.qcow2' index='3'/>
         <backingStore type='file' index='4'>
           <format type='qcow2'/>
           <source file='/var/run/kubevirt/container-disks/disk_1.img'/>
         </backingStore>
         <target dev='vda' bus='virtio'/>
         <alias name='ua-containerdisk'/>
         <address type='pci' domain='0x0000' bus='0x07' slot='0x00' function='0x0'/>
       </disk>
       <disk type='file' device='disk' model='virtio-non-transitional'>
         <driver name='qemu' type='raw' cache='none' error_policy='stop' discard='unmap'/>
         <source file='/var/run/kubevirt-ephemeral-disks/cloud-init-data/default/vm-cirros/noCloud.iso' index='2'/>
         <backingStore/>
         <target dev='vdb' bus='virtio'/>
         <alias name='ua-cloudinitdisk'/>
         <address type='pci' domain='0x0000' bus='0x08' slot='0x00' function='0x0'/>
       </disk>
       <disk type='file' device='disk'>
         <driver name='qemu' type='raw' cache='none' error_policy='stop' io='native' discard='unmap'/>
         <source file='/var/run/kubevirt-private/config-map-disks/config.iso' index='1'/>
         <backingStore/>
         <target dev='sda' bus='sata'/>
         <alias name='ua-config'/>
         <address type='drive' controller='0' bus='0' target='0' unit='0'/>
       </disk>
       <controller type='usb' index='0' model='none'>
         <alias name='usb'/>
       </controller>
       <controller type='scsi' index='0' model='virtio-non-transitional'>
         <alias name='scsi0'/>
         <address type='pci' domain='0x0000' bus='0x05' slot='0x00' function='0x0'/>
       </controller>
       <controller type='virtio-serial' index='0' model='virtio-non-transitional'>
         <alias name='virtio-serial0'/>
         <address type='pci' domain='0x0000' bus='0x06' slot='0x00' function='0x0'/>
       </controller>
       <controller type='sata' index='0'>
         <alias name='ide'/>
         <address type='pci' domain='0x0000' bus='0x00' slot='0x1f' function='0x2'/>
       </controller>
       <controller type='pci' index='0' model='pcie-root'>
         <alias name='pcie.0'/>
       </controller>
       <controller type='pci' index='1' model='pcie-root-port'>
         <model name='pcie-root-port'/>
         <target chassis='1' port='0x10'/>
         <alias name='pci.1'/>
         <address type='pci' domain='0x0000' bus='0x00' slot='0x02' function='0x0' multifunction='on'/>
       </controller>
       <controller type='pci' index='2' model='pcie-root-port'>
         <model name='pcie-root-port'/>
         <target chassis='2' port='0x11'/>
         <alias name='pci.2'/>
         <address type='pci' domain='0x0000' bus='0x00' slot='0x02' function='0x1'/>
       </controller>
       <controller type='pci' index='3' model='pcie-root-port'>
         <model name='pcie-root-port'/>
         <target chassis='3' port='0x12'/>
         <alias name='pci.3'/>
         <address type='pci' domain='0x0000' bus='0x00' slot='0x02' function='0x2'/>
       </controller>
       <controller type='pci' index='4' model='pcie-root-port'>
         <model name='pcie-root-port'/>
         <target chassis='4' port='0x13'/>
         <alias name='pci.4'/>
         <address type='pci' domain='0x0000' bus='0x00' slot='0x02' function='0x3'/>
       </controller>
       <controller type='pci' index='5' model='pcie-root-port'>
         <model name='pcie-root-port'/>
         <target chassis='5' port='0x14'/>
         <alias name='pci.5'/>
         <address type='pci' domain='0x0000' bus='0x00' slot='0x02' function='0x4'/>
       </controller>
       <controller type='pci' index='6' model='pcie-root-port'>
         <model name='pcie-root-port'/>
         <target chassis='6' port='0x15'/>
         <alias name='pci.6'/>
         <address type='pci' domain='0x0000' bus='0x00' slot='0x02' function='0x5'/>
       </controller>
       <controller type='pci' index='7' model='pcie-root-port'>
         <model name='pcie-root-port'/>
         <target chassis='7' port='0x16'/>
         <alias name='pci.7'/>
         <address type='pci' domain='0x0000' bus='0x00' slot='0x02' function='0x6'/>
       </controller>
       <controller type='pci' index='8' model='pcie-root-port'>
         <model name='pcie-root-port'/>
         <target chassis='8' port='0x17'/>
         <alias name='pci.8'/>
         <address type='pci' domain='0x0000' bus='0x00' slot='0x02' function='0x7'/>
       </controller>
       <controller type='pci' index='9' model='pcie-root-port'>
         <model name='pcie-root-port'/>
         <target chassis='9' port='0x18'/>
         <alias name='pci.9'/>
         <address type='pci' domain='0x0000' bus='0x00' slot='0x03' function='0x0' multifunction='on'/>
       </controller>
       <controller type='pci' index='10' model='pcie-root-port'>
         <model name='pcie-root-port'/>
         <target chassis='10' port='0x19'/>
         <alias name='pci.10'/>
         <address type='pci' domain='0x0000' bus='0x00' slot='0x03' function='0x1'/>
       </controller>
       <interface type='ethernet'>
         <mac address='e2:8d:0f:4c:8f:83'/>
         <target dev='tap0' managed='no'/>
         <model type='virtio-non-transitional'/>
         <mtu size='1480'/>
         <alias name='ua-default'/>
         <rom enabled='no'/>
         <address type='pci' domain='0x0000' bus='0x01' slot='0x00' function='0x0'/>
       </interface>
       <serial type='unix'>
         <source mode='bind' path='/var/run/kubevirt-private/c5bb78ad-8082-4965-92e9-dfad1e4b330d/virt-serial0'/>
         <log file='/var/run/kubevirt-private/c5bb78ad-8082-4965-92e9-dfad1e4b330d/virt-serial0-log' append='on'/>
         <target type='isa-serial' port='0'>
           <model name='isa-serial'/>
         </target>
         <alias name='serial0'/>
       </serial>
       <console type='unix'>
         <source mode='bind' path='/var/run/kubevirt-private/c5bb78ad-8082-4965-92e9-dfad1e4b330d/virt-serial0'/>
         <log file='/var/run/kubevirt-private/c5bb78ad-8082-4965-92e9-dfad1e4b330d/virt-serial0-log' append='on'/>
         <target type='serial' port='0'/>
         <alias name='serial0'/>
       </console>
       <channel type='unix'>
         <source mode='bind' path='/var/run/libvirt/qemu/run/channel/1-default_vm-cirros/org.qemu.guest_agent.0'/>
         <target type='virtio' name='org.qemu.guest_agent.0' state='disconnected'/>
         <alias name='channel0'/>
         <address type='virtio-serial' controller='0' bus='0' port='1'/>
       </channel>
       <input type='mouse' bus='ps2'>
         <alias name='input0'/>
       </input>
       <input type='keyboard' bus='ps2'>
         <alias name='input1'/>
       </input>
       <graphics type='vnc' socket='/var/run/kubevirt-private/c5bb78ad-8082-4965-92e9-dfad1e4b330d/virt-vnc'>
         <listen type='socket' socket='/var/run/kubevirt-private/c5bb78ad-8082-4965-92e9-dfad1e4b330d/virt-vnc'/>
       </graphics>
       <audio id='1' type='none'/>
       <video>
         <model type='vga' vram='16384' heads='1' primary='yes'/>
         <alias name='video0'/>
         <address type='pci' domain='0x0000' bus='0x00' slot='0x01' function='0x0'/>
       </video>
       <watchdog model='itco' action='reset'>
         <alias name='watchdog0'/>
       </watchdog>
       <memballoon model='virtio-non-transitional' freePageReporting='on'>
         <stats period='10'/>
         <alias name='balloon0'/>
         <address type='pci' domain='0x0000' bus='0x09' slot='0x00' function='0x0'/>
       </memballoon>
     </devices>
   </domain>
